# ===============================
# Namespace
# ===============================
apiVersion: v1
kind: Namespace
metadata:
  name: smartticket

---
# ===============================
# Mongo Deployment
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: smartticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017

---
# ===============================
# Mongo Service
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: smartticket
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP

---
# ===============================
# Backend Deployment
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: smartticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: malik0505/smartticket-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: mongodb://mongo:27017/smartticket

---
# ===============================
# Backend Service
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: smartticket
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---
# ===============================
# Frontend Deployment
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: smartticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: malik0505/smartticket-frontend:latest
        ports:
        - containerPort: 80

---
# ===============================
# Frontend Service (User Access)
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: smartticket
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31390
  type: NodePort

